org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11

mod_version=1.0.0
maven_group=com.alex.fluidworks
archives_base_name=fluid-works
easy_containers_version=1.3.0
fluid_api_jar=fabric-fluid-api-1.3.0.jar
temperature_api_jar=temperature-api-1.0.0-dev.jar
